baseurl = "https://upasana-parashar.edufor.me"
DefaultContentLanguage = "en"
title = "My Best Blog"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "I made this in $$H^UG_O$$"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Upasana Parashar"
  website = "upasanaparashar.edufor.me"
  email = "upasana_parashar@edufor.me"
  github = "UpasanaParashar"
  #twitter = "username"
  #linkedin = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #mastodon = "url"
  #kaggle = "username"

[[menu.main]]
    name = "Blog"
    url = "/post"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    url="page/sample-page"
    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
